deepseek:
  api-key:
  model: deepseek-chat
  base-url: https://api.deepseek.com  # 可选，默认为官方 API 地址
  log-requests: true
  log-responses: true
  log-level: DEBUG
  connect-timeout: 600
  read-timeout: 600
  call-timeout: 600
server:
  port: 5001
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/xx?currentSchema=public&allowMultiQueries=true
    driver-class-name: org.postgresql.Driver
    username:
    password:
  profiles:
    include:
      - prompt
